delete from questions;

insert into questions (game_type, order_index, content) values
('bible_quiz', 0, '{"question":"Siapa yang menciptakan langit dan bumi pada mulanya?","options":["Malaikat","Allah","Musa","Nuh"],"answer_index":1,"reference":"Kejadian 1:1"}'),
('bible_quiz', 1, '{"question":"Dari apa Allah membuat tubuh Adam?","options":["Air","Debu tanah","Kayu","Batu"],"answer_index":1,"reference":"Kejadian 2:7"}'),
('bible_quiz', 2, '{"question":"Buah apa yang dimakan Adam dan Hawa di taman Eden?","options":["Anggur","Apel","Buah dari pohon pengetahuan baik dan jahat","Ara"],"answer_index":2,"reference":"Kejadian 3:6"}'),
('bible_quiz', 3, '{"question":"Siapa anak Kain yang membunuh Abel?","options":["Kain","Set","Lamekh","Henokh"],"answer_index":0,"reference":"Kejadian 4:8"}'),
('bible_quiz', 4, '{"question":"Berapa lama hujan turun saat zaman Nuh?","options":["20 hari 20 malam","30 hari 30 malam","40 hari 40 malam","7 hari 7 malam"],"answer_index":2,"reference":"Kejadian 7:12"}'),
('bible_quiz', 5, '{"question":"Berapa banyak orang yang diselamatkan di dalam bahtera Nuh?","options":["4 orang","6 orang","8 orang","10 orang"],"answer_index":2,"reference":"1 Petrus 3:20"}'),
('bible_quiz', 6, '{"question":"Apa tanda perjanjian Allah dengan Nuh setelah air bah?","options":["Matahari","Bintang","Pelangi","Awan putih"],"answer_index":2,"reference":"Kejadian 9:13"}'),
('bible_quiz', 7, '{"question":"Siapa yang dipanggil Allah untuk meninggalkan negerinya menuju tanah yang dijanjikan?","options":["Nuh","Ishak","Abraham","Yakub"],"answer_index":2,"reference":"Kejadian 12:1"}'),
('bible_quiz', 8, '{"question":"Apa nama istri Abraham?","options":["Hagar","Ribka","Sara","Lea"],"answer_index":2,"reference":"Kejadian 17:15"}'),
('bible_quiz', 9, '{"question":"Siapa anak yang dijanjikan Allah kepada Abraham dan Sara di hari tua mereka?","options":["Ismail","Ishak","Yakub","Esau"],"answer_index":1,"reference":"Kejadian 21:3"}'),
('bible_quiz', 10, '{"question":"Apa yang disiapkan Allah sebagai pengganti Ishak ketika Abraham hendak mempersembahkannya?","options":["Lembu","Domba","Kambing","Seekor domba jantan di semak"],"answer_index":3,"reference":"Kejadian 22:13"}'),
('bible_quiz', 11, '{"question":"Siapa yang menjual hak kesulungannya dengan semangkuk sup merah?","options":["Yakub","Esau","Ruben","Yehuda"],"answer_index":1,"reference":"Kejadian 25:33"}'),
('bible_quiz', 12, '{"question":"Siapa yang bermimpi tentang tangga yang menghubungkan bumi dan surga?","options":["Yusuf","Abraham","Ishak","Yakub"],"answer_index":3,"reference":"Kejadian 28:12"}'),
('bible_quiz', 13, '{"question":"Apa yang membuat Yusuf dibenci oleh saudara-saudaranya?","options":["Ia makan lebih banyak","Ia malas bekerja","Ayahnya memberinya jubah indah dan ia dikasihi lebih","Ia sering berbohong"],"answer_index":2,"reference":"Kejadian 37:3-4"}'),
('bible_quiz', 14, '{"question":"Siapa yang menjual Yusuf kepada pedagang Ismael?","options":["Ruben","Benyamin","Saudara-saudaranya","Yakub"],"answer_index":2,"reference":"Kejadian 37:28"}'),
('bible_quiz', 15, '{"question":"Kepada siapa Yusuf menafsirkan mimpi tentang tujuh ekor sapi gemuk dan tujuh ekor sapi kurus?","options":["Raja Nebukadnezar","Firaun","Raja Babel","Herodes"],"answer_index":1,"reference":"Kejadian 41:15"}'),
('bible_quiz', 16, '{"question":"Apa arti mimpi tujuh bulir gandum penuh dan tujuh bulir gandum hampa yang ditafsirkan Yusuf?","options":["Perang dan damai","7 tahun kemakmuran lalu 7 tahun kelaparan","7 tahun kelaparan lalu 7 tahun kemakmuran","Pergantian raja"],"answer_index":1,"reference":"Kejadian 41:29-30"}'),
('bible_quiz', 17, '{"question":"Di mana Musa melihat semak yang terbakar tetapi tidak hangus?","options":["Gunung Sinai","Gunung Horeb","Lembah Yordan","Padang Midian"],"answer_index":1,"reference":"Keluaran 3:2"}'),
('bible_quiz', 18, '{"question":"Berapa banyak tulah yang Allah kirimkan kepada Mesir?","options":["7","9","10","12"],"answer_index":2,"reference":"Keluaran 7-12"}'),
('bible_quiz', 19, '{"question":"Apa tulah terakhir yang menimpa Mesir sebelum bangsa Israel keluar?","options":["Kegelapan","Belalang","Kematian anak sulung","Hujan es"],"answer_index":2,"reference":"Keluaran 12:29"}'),
('bible_quiz', 20, '{"question":"Bagaimana Allah membelah Laut Merah agar bangsa Israel dapat menyeberang?","options":["Dengan doa Harun","Musa memukul laut dengan tongkatnya","Allah meniupkan angin timur yang kuat","Musa berdoa seharian"],"answer_index":2,"reference":"Keluaran 14:21"}'),
('bible_quiz', 21, '{"question":"Makanan apa yang Allah berikan dari langit kepada bangsa Israel di padang gurun?","options":["Roti biasa","Manna","Daging kambing","Buah ara"],"answer_index":1,"reference":"Keluaran 16:15"}'),
('bible_quiz', 22, '{"question":"Di gunung mana Allah memberikan Sepuluh Perintah kepada Musa?","options":["Gunung Karmel","Gunung Horeb","Gunung Sinai","Gunung Zion"],"answer_index":2,"reference":"Keluaran 19:20"}'),
('bible_quiz', 23, '{"question":"Apa perintah pertama dari Sepuluh Perintah Allah?","options":["Jangan membunuh","Hormati ayah ibumu","Jangan ada padamu allah lain di hadapan-Ku","Kuduskan hari Sabat"],"answer_index":2,"reference":"Keluaran 20:3"}'),
('bible_quiz', 24, '{"question":"Apa yang dibuat Musa dari perunggu untuk menyembuhkan orang Israel yang digigit ular?","options":["Patung lembu perunggu","Ular perunggu di tiang","Tombak perunggu","Mahkota perunggu"],"answer_index":1,"reference":"Bilangan 21:9"}'),
('bible_quiz', 25, '{"question":"Siapa yang menggantikan Musa memimpin bangsa Israel masuk ke tanah Kanaan?","options":["Kaleb","Eleazar","Yosua","Pinehas"],"answer_index":2,"reference":"Yosua 1:1-2"}'),
('bible_quiz', 26, '{"question":"Berapa kali bangsa Israel harus mengelilingi kota Yerikho sebelum temboknya runtuh?","options":["7 hari, 1x sehari, lalu 7x di hari ke-7","3 hari","10 kali","40 kali"],"answer_index":0,"reference":"Yosua 6:3-4"}'),
('bible_quiz', 27, '{"question":"Siapa hakim perempuan Israel yang memimpin bangsa Israel mengalahkan musuh?","options":["Rut","Ester","Miriam","Debora"],"answer_index":3,"reference":"Hakim-hakim 4:4"}'),
('bible_quiz', 28, '{"question":"Dengan berapa orang Gideon mengalahkan tentara Midian yang berjumlah sangat banyak?","options":["100 orang","300 orang","1000 orang","3000 orang"],"answer_index":1,"reference":"Hakim-hakim 7:7"}'),
('bible_quiz', 29, '{"question":"Siapa yang memotong rambut Simson sehingga ia kehilangan kekuatannya?","options":["Rahab","Debora","Dalila","Rut"],"answer_index":2,"reference":"Hakim-hakim 16:19"}'),
('bible_quiz', 30, '{"question":"Apa kalimat terkenal Rut kepada Naomi yang menunjukkan kesetiaan?","options":["Ke mana engkau pergi, aku pun pergi","Aku akan kembali ke negeriku","Tuhan memberkatimu","Pergilah tanpaku"],"answer_index":0,"reference":"Rut 1:16"}'),
('bible_quiz', 31, '{"question":"Siapa yang mengurapi Saul menjadi raja Israel pertama?","options":["Elia","Nabi Gad","Samuel","Imam Sadok"],"answer_index":2,"reference":"1 Samuel 10:1"}'),
('bible_quiz', 32, '{"question":"Berapa tinggi Goliat orang Filistin yang dilawan Daud?","options":["Sekitar 2 meter","Lebih dari 2,7 meter (enam hasta sejengkal)","Sama tinggi dengan Daud","1,8 meter"],"answer_index":1,"reference":"1 Samuel 17:4"}'),
('bible_quiz', 33, '{"question":"Senjata apa yang digunakan Daud untuk membunuh Goliat?","options":["Pedang","Tombak","Ketapel dan batu","Panah"],"answer_index":2,"reference":"1 Samuel 17:50"}'),
('bible_quiz', 34, '{"question":"Mazmur 23 dimulai dengan kalimat apa?","options":["TUHAN adalah terangku","Tuhan adalah gembalaku","Allah adalah perlindunganku","Berbahagialah orang yang takut akan TUHAN"],"answer_index":1,"reference":"Mazmur 23:1"}'),
('bible_quiz', 35, '{"question":"Siapa yang meminta hikmat kepada Allah ketika baru menjadi raja?","options":["Daud","Saul","Salomo","Rehabeam"],"answer_index":2,"reference":"1 Raja-raja 3:9"}'),
('bible_quiz', 36, '{"question":"Berapa banyak nabi Baal yang dilawan Elia di Gunung Karmel?","options":["100 orang","400 orang","450 orang","1000 orang"],"answer_index":2,"reference":"1 Raja-raja 18:22"}'),
('bible_quiz', 37, '{"question":"Bagaimana Allah berbicara kepada Elia di gua Gunung Horeb?","options":["Dalam api besar","Dalam angin kencang","Dalam gempa bumi","Dalam suara yang halus dan lembut"],"answer_index":3,"reference":"1 Raja-raja 19:12"}'),
('bible_quiz', 38, '{"question":"Apa yang dilakukan Ratu Ester yang berani walaupun bisa dihukum mati?","options":["Bernyanyi di hadapan raja","Datang menghadap raja tanpa dipanggil untuk menyelamatkan bangsanya","Membangun bait Allah","Menulis surat kepada raja"],"answer_index":1,"reference":"Ester 4:16"}'),
('bible_quiz', 39, '{"question":"Mengapa Daniel dilempar ke dalam gua singa?","options":["Karena ia mencuri","Karena ia berdoa kepada Allah tiga kali sehari meskipun dilarang","Karena ia tidak menghormati raja","Karena ia berbohong kepada raja"],"answer_index":1,"reference":"Daniel 6:10"}'),
('bible_quiz', 40, '{"question":"Siapa yang menemani Daniel tidak mau makan makanan najis dari meja raja Babel?","options":["Petrus, Yohanes, dan Yakobus","Sadrakh, Mesakh, dan Abednego","Kaleb, Yosua, dan Pinehas","Ruben, Simeon, dan Lewi"],"answer_index":1,"reference":"Daniel 1:6-8"}'),
('bible_quiz', 41, '{"question":"Apa yang terjadi kepada Sadrakh, Mesakh, dan Abednego di dalam perapian yang menyala-nyala?","options":["Mereka hangus terbakar","Mereka diselamatkan dan seseorang seperti anak allah berjalan bersama mereka","Mereka pingsan","Mereka mati tapi dibangkitkan"],"answer_index":1,"reference":"Daniel 3:25"}'),
('bible_quiz', 42, '{"question":"Ke kota mana Yunus diperintahkan Allah untuk pergi berkhotbah?","options":["Babel","Yerusalem","Niniwe","Tirus"],"answer_index":2,"reference":"Yunus 1:2"}'),
('bible_quiz', 43, '{"question":"Berapa lama Yunus berada di dalam perut ikan besar?","options":["1 hari 1 malam","3 hari 3 malam","7 hari 7 malam","40 hari 40 malam"],"answer_index":1,"reference":"Yunus 1:17"}'),
('bible_quiz', 44, '{"question":"Di mana Yesus dilahirkan?","options":["Nazaret","Yerusalem","Betlehem","Kapernaum"],"answer_index":2,"reference":"Lukas 2:4-6"}'),
('bible_quiz', 45, '{"question":"Di mana bayi Yesus dibaringkan setelah lahir?","options":["Di tempat tidur mewah","Di palungan","Di atas batu","Di tanah"],"answer_index":1,"reference":"Lukas 2:7"}'),
('bible_quiz', 46, '{"question":"Siapa yang memberi tahu para gembala tentang kelahiran Yesus?","options":["Bintang di timur","Para orang majus","Malaikat","Raja Herodes"],"answer_index":2,"reference":"Lukas 2:10"}'),
('bible_quiz', 47, '{"question":"Apa yang diikuti para orang Majus untuk menemukan bayi Yesus?","options":["Suara malaikat","Bintang di timur","Peta dari imam","Mimpi"],"answer_index":1,"reference":"Matius 2:2"}'),
('bible_quiz', 48, '{"question":"Di sungai mana Yesus dibaptis?","options":["Sungai Efrat","Sungai Nil","Sungai Yordan","Sungai Gihon"],"answer_index":2,"reference":"Matius 3:13"}'),
('bible_quiz', 49, '{"question":"Siapa yang membaptis Yesus?","options":["Petrus","Yohanes Pembaptis","Paulus","Yakobus"],"answer_index":1,"reference":"Matius 3:13"}'),
('bible_quiz', 50, '{"question":"Berapa hari Yesus berpuasa di padang gurun saat dicobai Iblis?","options":["7 hari","20 hari","40 hari","3 hari"],"answer_index":2,"reference":"Matius 4:2"}'),
('bible_quiz', 51, '{"question":"Apa mukjizat pertama Yesus yang dicatat dalam Injil Yohanes?","options":["Menyembuhkan orang buta","Mengubah air menjadi anggur di Kana","Memberi makan 5000 orang","Membangkitkan Lazarus"],"answer_index":1,"reference":"Yohanes 2:9"}'),
('bible_quiz', 52, '{"question":"Berapa banyak orang yang diberi makan Yesus dengan lima roti dan dua ikan?","options":["1000 orang","3000 orang","5000 orang","10000 orang"],"answer_index":2,"reference":"Yohanes 6:10"}'),
('bible_quiz', 53, '{"question":"Dalam perumpamaan Anak yang Hilang, apa yang dilakukan ayah ketika melihat anaknya pulang dari jauh?","options":["Marah dan menutup pintu","Menyuruh hamba mengusirnya","Berlari menyongsong dan memeluknya","Berdiam diri"],"answer_index":2,"reference":"Lukas 15:20"}'),
('bible_quiz', 54, '{"question":"Dalam perumpamaan Orang Samaria yang Baik Hati, siapa yang menolong orang yang dirampok di jalan?","options":["Seorang imam","Seorang Lewi","Seorang Samaria","Seorang prajurit"],"answer_index":2,"reference":"Lukas 10:33"}'),
('bible_quiz', 55, '{"question":"Dalam perumpamaan Penabur, benih yang jatuh di tanah yang baik menghasilkan berapa kali lipat?","options":["10, 20, 30 kali lipat","30, 60, 100 kali lipat","5, 10, 15 kali lipat","2, 4, 8 kali lipat"],"answer_index":1,"reference":"Matius 13:8"}'),
('bible_quiz', 56, '{"question":"Berapa lama Lazarus sudah di dalam kubur ketika Yesus membangkitkannya?","options":["1 hari","2 hari","3 hari","4 hari"],"answer_index":3,"reference":"Yohanes 11:39"}'),
('bible_quiz', 57, '{"question":"Apa yang diucapkan Yesus sebelum Lazarus keluar dari kubur?","options":["Lazarus, bangkitlah!","Lazarus, keluarlah!","Lazarus, hiduplah!","Lazarus, bangun!"],"answer_index":1,"reference":"Yohanes 11:43"}'),
('bible_quiz', 58, '{"question":"Kalimat pertama Ucapan Bahagia (Khotbah di Bukit) adalah?","options":["Berbahagialah orang yang lapar dan haus","Berbahagialah orang yang miskin di hadapan Allah","Berbahagialah orang yang murni hatinya","Berbahagialah orang yang membawa damai"],"answer_index":1,"reference":"Matius 5:3"}'),
('bible_quiz', 59, '{"question":"Dalam Doa Bapa Kami, setelah \"Jadilah kehendak-Mu\" lanjutannya adalah?","options":["Di bumi seperti di surga","Di surga dan di bumi","Di mana-mana","Selamanya"],"answer_index":0,"reference":"Matius 6:10"}'),
('bible_quiz', 60, '{"question":"Yesus berubah rupa di atas gunung bersama siapa?","options":["Petrus, Yohanes, Yakobus","Petrus, Andreas, Yohanes","Matius, Markus, Lukas","12 murid"],"answer_index":0,"reference":"Matius 17:1-2"}'),
('bible_quiz', 61, '{"question":"Siapa yang mengkhianati Yesus dengan ciuman?","options":["Petrus","Tomas","Yudas Iskariot","Bartolomeus"],"answer_index":2,"reference":"Matius 26:49"}'),
('bible_quiz', 62, '{"question":"Berapa kali Petrus menyangkal Yesus sebelum ayam berkokok?","options":["1 kali","2 kali","3 kali","4 kali"],"answer_index":2,"reference":"Matius 26:75"}'),
('bible_quiz', 63, '{"question":"Di mana Yesus disalibkan?","options":["Di Betlehem","Di Getsemani","Di Golgota","Di Nazaret"],"answer_index":2,"reference":"Yohanes 19:17"}'),
('bible_quiz', 64, '{"question":"Siapa yang pertama kali melihat Yesus setelah kebangkitan-Nya?","options":["Petrus","Yohanes","Maria Magdalena","Para murid"],"answer_index":2,"reference":"Yohanes 20:14"}'),
('bible_quiz', 65, '{"question":"Apa yang terjadi pada hari Pentakosta?","options":["Yesus naik ke surga","Roh Kudus turun atas para murid","Gereja pertama didirikan di Roma","Petrus mati syahid"],"answer_index":1,"reference":"Kisah Para Rasul 2:4"}'),
('bible_quiz', 66, '{"question":"Berapa banyak jiwa yang bertobat pada hari Pentakosta setelah Petrus berkhotbah?","options":["1000 jiwa","2000 jiwa","3000 jiwa","5000 jiwa"],"answer_index":2,"reference":"Kisah Para Rasul 2:41"}'),
('bible_quiz', 67, '{"question":"Di jalan mana Saulus (Paulus) mengalami penglihatan dan bertobat?","options":["Jalan ke Yerusalem","Jalan ke Roma","Jalan ke Damsyik","Jalan ke Antiokhia"],"answer_index":2,"reference":"Kisah Para Rasul 9:3"}'),
('bible_quiz', 68, '{"question":"Apa yang dilakukan Paulus dan Silas di penjara Filipi tengah malam?","options":["Menangis dan berdoa","Bernyanyi puji-pujian dan berdoa","Tidur","Meminta tolong sipir"],"answer_index":1,"reference":"Kisah Para Rasul 16:25"}'),
('bible_quiz', 69, '{"question":"Apa yang terjadi setelah Paulus dan Silas berdoa dan menyanyi di penjara?","options":["Pintu terbuka sendiri","Gempa bumi dan pintu-pintu terbuka, rantai lepas","Malaikat datang membebaskan","Sipir melepaskan mereka"],"answer_index":1,"reference":"Kisah Para Rasul 16:26"}'),
('bible_quiz', 70, '{"question":"Dalam kitab Wahyu, berapa banyak jemaat yang menerima surat dari Yohanes?","options":["5 jemaat","6 jemaat","7 jemaat","12 jemaat"],"answer_index":2,"reference":"Wahyu 1:11"}'),
('bible_quiz', 71, '{"question":"Berapakah bilangan binatang buas dalam Kitab Wahyu yang terkenal?","options":["666","777","888","999"],"answer_index":0,"reference":"Wahyu 13:18"}'),
('bible_quiz', 72, '{"question":"Bagaimana Yesus memanggil Zakheus yang bertubuh pendek untuk turun dari pohon?","options":["Ia melambaikan tangan","Ia memanggil namanya dan berkata ia mau menumpang di rumahnya","Ia menyuruh murid-murid memanggilnya","Ia tidak memanggilnya, Zakheus yang turun sendiri"],"answer_index":1,"reference":"Lukas 19:5"}'),
('bible_quiz', 73, '{"question":"Yesus berkata Aku adalah jalan, kebenaran, dan hidup ada di kitab mana?","options":["Matius 14:6","Yohanes 14:6","Lukas 14:6","Markus 14:6"],"answer_index":1,"reference":"Yohanes 14:6"}'),
('bible_quiz', 74, '{"question":"Ayat Yohanes 3:16 berisi tentang apa?","options":["Perintah kasih","Kasih Allah yang memberikan Anak-Nya sehingga siapa percaya tidak binasa","Doa Bapa Kami","Hukum Taurat"],"answer_index":1,"reference":"Yohanes 3:16"}'),
('bible_quiz', 75, '{"question":"Siapa yang berjalan di atas air mendatangi Yesus lalu tenggelam karena ragu?","options":["Yohanes","Andreas","Petrus","Yakub"],"answer_index":2,"reference":"Matius 14:29-30"}'),
('bible_quiz', 76, '{"question":"Dalam perumpamaan domba yang hilang, berapa banyak domba yang dimiliki gembala?","options":["10 ekor","50 ekor","100 ekor","1000 ekor"],"answer_index":2,"reference":"Lukas 15:4"}'),
('bible_quiz', 77, '{"question":"Apa yang Yesus gunakan dalam Perjamuan Terakhir sebagai lambang tubuh-Nya?","options":["Daging kambing","Roti","Anggur","Ikan"],"answer_index":1,"reference":"Lukas 22:19"}'),
('bible_quiz', 78, '{"question":"Di mana Yesus berdoa dengan sungguh-sungguh sebelum ditangkap?","options":["Di Golgota","Di Betlehem","Di Taman Getsemani","Di Kapernaum"],"answer_index":2,"reference":"Matius 26:36"}'),
('bible_quiz', 79, '{"question":"Apa perintah terakhir Yesus kepada murid-murid sebelum naik ke surga?","options":["Pergi dan jadikanlah semua bangsa murid-Ku","Berdoa setiap saat","Membangun gereja di Roma","Membaca Alkitab setiap hari"],"answer_index":0,"reference":"Matius 28:19"}'),
('bible_quiz', 80, '{"question":"Siapa yang memuji kelahiran Yesus dengan berkata Kemuliaan bagi Allah di tempat yang maha tinggi?","options":["Para orang Majus","Herodes","Para malaikat","Para imam"],"answer_index":2,"reference":"Lukas 2:14"}'),
('bible_quiz', 81, '{"question":"Elija (Elia) dari berapa langit diperlihatkan dalam transfigurasi bersama Musa?","options":["Elia tidak hadir","Elia hadir bersama Musa","Hanya Musa yang hadir","Hanya Elia yang hadir"],"answer_index":1,"reference":"Matius 17:3"}'),
('bible_quiz', 82, '{"question":"Naomi berkata kepada Rut dan Orpa supaya pulang ke rumah ibu mereka, tetapi siapa yang tetap bersama Naomi?","options":["Orpa","Rut","Keduanya tetap","Keduanya pergi"],"answer_index":1,"reference":"Rut 1:14"}'),
('bible_quiz', 83, '{"question":"Apa isi tulisan yang muncul di dinding istana Babel saat pesta raja Belsyazar?","options":["Dosa raja","Mene, mene, tekel, uparsin","Hari penghakiman","Nama Allah"],"answer_index":1,"reference":"Daniel 5:25"}'),
('bible_quiz', 84, '{"question":"Yesus mengusir pedagang dan penukar uang dari mana?","options":["Dari kota Yerusalem","Dari Bait Suci","Dari rumah Herodes","Dari sinagoge"],"answer_index":1,"reference":"Yohanes 2:15"}'),
('bible_quiz', 85, '{"question":"Siapa yang menyambut Yesus masuk Yerusalem dengan melambai-lambaikan daun palem?","options":["Para imam","Orang banyak","Para murid saja","Para prajurit Roma"],"answer_index":1,"reference":"Yohanes 12:13"}'),
('bible_quiz', 86, '{"question":"Berapa banyak tahun bangsa Israel mengembara di padang gurun?","options":["20 tahun","40 tahun","70 tahun","100 tahun"],"answer_index":1,"reference":"Bilangan 14:33"}'),
('bible_quiz', 87, '{"question":"Siapa yang membawa kabar gembira kepada Maria bahwa ia akan mengandung Anak Allah?","options":["Malaikat Mikhael","Malaikat Gabriel","Malaikat Rafael","Roh Kudus langsung"],"answer_index":1,"reference":"Lukas 1:26"}'),
('bible_quiz', 88, '{"question":"Apa yang diucapkan Maria ketika mendengar kabar dari malaikat?","options":["Aku tidak percaya","Sesungguhnya aku adalah hamba Tuhan, jadilah kepadaku seperti yang engkau katakan","Aku takut","Tolong tanya suamiku dulu"],"answer_index":1,"reference":"Lukas 1:38"}'),
('bible_quiz', 89, '{"question":"Dalam kitab Kejadian, apa pekerjaan Adam di taman Eden sebelum jatuh dalam dosa?","options":["Membangun rumah","Memelihara dan mengusahakan taman itu","Berburu binatang","Mencari ikan"],"answer_index":1,"reference":"Kejadian 2:15"}'),
('bible_quiz', 90, '{"question":"Yesus berkata kepada wanita Samaria bahwa Ia dapat memberikan apa?","options":["Roti hidup","Air hidup","Kehidupan kekal","Kebenaran sejati"],"answer_index":1,"reference":"Yohanes 4:10"}'),
('bible_quiz', 91, '{"question":"Siapa orang yang pertama dibunuh dalam Alkitab?","options":["Kain","Abel","Adam","Set"],"answer_index":1,"reference":"Kejadian 4:8"}'),
('bible_quiz', 92, '{"question":"Ketika Daud masih muda sebelum melawan Goliat, ia adalah seorang apa?","options":["Prajurit","Gembala domba","Tukang batu","Pedagang"],"answer_index":1,"reference":"1 Samuel 17:15"}'),
('bible_quiz', 93, '{"question":"Apa perintah terbesar menurut Yesus?","options":["Jangan membunuh","Kasihilah Tuhan Allahmu dengan segenap hatimu","Hormati orang tua","Kasihilah sesamamu"],"answer_index":1,"reference":"Matius 22:37"}'),
('bible_quiz', 94, '{"question":"Yesus berkata Aku adalah terang dunia ada di kitab mana?","options":["Matius 8:12","Lukas 8:12","Yohanes 8:12","Markus 8:12"],"answer_index":2,"reference":"Yohanes 8:12"}'),
('bible_quiz', 95, '{"question":"Siapa yang diurapi menjadi raja Daud oleh Samuel?","options":["Anak sulung Isai","Anak yang paling tampan","Daud, anak bungsu Isai","Anak yang paling tinggi"],"answer_index":2,"reference":"1 Samuel 16:12-13"}'),
('bible_quiz', 96, '{"question":"Apakah yang Yesus katakan saat Ia dibaptis terdengar dari surga?","options":["Inilah Anak-Ku yang Kukasihi, kepada-Nyalah Aku berkenan","Dengarkanlah Dia","Ia adalah Raja","Ia adalah Nabi"],"answer_index":0,"reference":"Matius 3:17"}'),
('bible_quiz', 97, '{"question":"Siapa nama anak yang dijanjikan kepada Zakharia dan Elisabet di hari tua mereka?","options":["Yesus","Yohanes","Yakobus","Yusuf"],"answer_index":1,"reference":"Lukas 1:13"}'),
('bible_quiz', 98, '{"question":"Di mana Paulus dan Silas dipenjara lalu dibebaskan oleh gempa bumi?","options":["Korintus","Efesus","Filipi","Tesalonika"],"answer_index":2,"reference":"Kisah Para Rasul 16:23-26"}'),
('bible_quiz', 99, '{"question":"Kitab apa yang dimulai dengan kata Pada mulanya adalah Firman?","options":["Kejadian","Ibrani","Yohanes","Wahyu"],"answer_index":2,"reference":"Yohanes 1:1"}');

insert into questions (game_type, order_index, content) values
('verse_scramble', 0, '{"reference":"Yohanes 3:16","words":["Karena","begitu","besar","kasih","Allah","akan","dunia","ini"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 1, '{"reference":"Yohanes 14:6","words":["Akulah","jalan","kebenaran","dan","hidup"],"correct_order":[0,1,2,3,4]}'),
('verse_scramble', 2, '{"reference":"Mazmur 23:1","words":["TUHAN","adalah","gembalaku","takkan","kekurangan","aku"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 3, '{"reference":"Kejadian 1:1","words":["Pada","mulanya","Allah","menciptakan","langit","dan","bumi"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 4, '{"reference":"Filipi 4:13","words":["Segala","perkara","dapat","kutanggung","di","dalam","Dia","yang","memberi","kekuatan","kepadaku"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 5, '{"reference":"Yeremia 29:11","words":["Aku","mengetahui","rancangan-rancangan","apa","yang","ada","pada-Ku","mengenai","kamu"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 6, '{"reference":"Mazmur 119:105","words":["Firman-Mu","adalah","pelita","bagi","kakiku","dan","terang","bagi","jalanku"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 7, '{"reference":"Yosua 1:9","words":["Kuatkan","dan","teguhkanlah","hatimu","janganlah","kecut","dan","tawar","hati"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 8, '{"reference":"Roma 8:28","words":["Allah","turut","bekerja","dalam","segala","sesuatu","untuk","mendatangkan","kebaikan"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 9, '{"reference":"Yesaya 40:31","words":["Orang","yang","menanti-nantikan","TUHAN","mendapat","kekuatan","baru"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 10, '{"reference":"Matius 6:33","words":["Carilah","dahulu","Kerajaan","Allah","dan","kebenarannya"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 11, '{"reference":"Amsal 3:5","words":["Percayalah","kepada","TUHAN","dengan","segenap","hatimu"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 12, '{"reference":"Amsal 3:6","words":["Akuilah","Dia","dalam","segala","lakumu","maka","Ia","akan","meluruskan","jalanmu"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 13, '{"reference":"Filipi 4:6","words":["Janganlah","hendaknya","kamu","kuatir","tentang","apapun","juga"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 14, '{"reference":"Filipi 4:4","words":["Bersukacitalah","senantiasa","dalam","Tuhan","sekali","lagi","kukatakan","bersukacitalah"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 15, '{"reference":"Yesaya 41:10","words":["Janganlah","takut","sebab","Aku","menyertai","engkau"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 16, '{"reference":"Mazmur 27:1","words":["TUHAN","adalah","terangku","dan","keselamatanku","kepada","siapakah","aku","harus","takut"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 17, '{"reference":"Yohanes 11:25","words":["Akulah","kebangkitan","dan","hidup","barangsiapa","percaya","kepada-Ku","ia","akan","hidup"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 18, '{"reference":"Wahyu 3:20","words":["Lihat","Aku","berdiri","di","muka","pintu","dan","mengetuk"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 19, '{"reference":"Matius 28:19","words":["Jadikanlah","semua","bangsa","murid-Ku","dan","baptislah","mereka"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 20, '{"reference":"Markus 16:15","words":["Pergilah","ke","seluruh","dunia","beritakanlah","Injil","kepada","segala","makhluk"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 21, '{"reference":"Kisah Para Rasul 1:8","words":["Kamu","akan","menjadi","saksi-Ku","di","Yerusalem","dan","Yudea","dan","Samaria"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 22, '{"reference":"Ibrani 11:1","words":["Iman","adalah","dasar","dari","segala","sesuatu","yang","kita","harapkan"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 23, '{"reference":"Roma 12:1","words":["Persembahkanlah","tubuhmu","sebagai","persembahan","yang","hidup","kudus","dan","berkenan","kepada","Allah"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 24, '{"reference":"Roma 12:2","words":["Janganlah","kamu","menjadi","serupa","dengan","dunia","ini"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 25, '{"reference":"Efesus 2:8","words":["Sebab","karena","kasih","karunia","kamu","diselamatkan","oleh","iman"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 26, '{"reference":"Efesus 6:11","words":["Kenakanlah","seluruh","perlengkapan","senjata","Allah","supaya","kamu","dapat","berdiri"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 27, '{"reference":"2 Timotius 3:16","words":["Segala","tulisan","yang","diilhamkan","Allah","memang","bermanfaat"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 28, '{"reference":"1 Korintus 13:4","words":["Kasih","itu","sabar","kasih","itu","murah","hati"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 29, '{"reference":"1 Korintus 13:13","words":["Demikianlah","tinggal","ketiga","hal","ini","iman","pengharapan","dan","kasih"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 30, '{"reference":"Yesaya 53:5","words":["Tetapi","ia","tertikam","oleh","karena","pemberontakan","kita"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 31, '{"reference":"Mazmur 46:1","words":["Allah","itu","bagi","kita","tempat","perlindungan","dan","kekuatan"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 32, '{"reference":"Mazmur 91:1","words":["Orang","yang","duduk","dalam","lindungan","Yang","Mahatinggi"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 33, '{"reference":"Mazmur 91:2","words":["Aku","berkata","kepada","TUHAN","Engkaulah","tempat","perlindunganku","dan","kubu","pertahananku"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 34, '{"reference":"Amsal 18:10","words":["Nama","TUHAN","adalah","menara","yang","kuat"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 35, '{"reference":"Lukas 1:37","words":["Sebab","bagi","Allah","tidak","ada","yang","mustahil"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 36, '{"reference":"Matius 5:14","words":["Kamu","adalah","terang","dunia","Kota","yang","terletak","di","atas","gunung"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 37, '{"reference":"Matius 22:37","words":["Kasihilah","Tuhan","Allahmu","dengan","segenap","hatimu","dan","dengan","segenap","jiwamu"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 38, '{"reference":"Ulangan 6:5","words":["Kasihilah","TUHAN","Allahmu","dengan","segenap","hatimu","dan","segenap","jiwamu"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 39, '{"reference":"Ulangan 31:6","words":["Kuatkan","dan","teguhkanlah","hatimu","janganlah","takut","dan","jangan","gemetar"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 40, '{"reference":"Yosua 24:15","words":["Tetapi","aku","dan","seisi","rumahku","kami","akan","beribadah","kepada","TUHAN"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 41, '{"reference":"Daniel 3:17","words":["Jika","Allah","kami","yang","kami","puja","sanggup","melepaskan","kami"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 42, '{"reference":"Amsal 22:6","words":["Didiklah","orang","muda","menurut","jalan","yang","patut"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 43, '{"reference":"Mazmur 23:4","words":["Sekalipun","aku","berjalan","dalam","lembah","kekelaman","aku","tidak","takut"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 44, '{"reference":"1 Yohanes 1:9","words":["Jika","kita","mengaku","dosa","kita","maka","Ia","setia","dan","adil"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 45, '{"reference":"1 Yohanes 4:8","words":["Barangsiapa","tidak","mengasihi","ia","tidak","mengenal","Allah","sebab","Allah","adalah","kasih"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 46, '{"reference":"Yakobus 1:2","words":["Saudara-saudaraku","anggaplah","sebagai","suatu","kebahagiaan","apabila","kamu","jatuh","ke","dalam","berbagai","pencobaan"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10,11]}'),
('verse_scramble', 47, '{"reference":"Matius 6:9","words":["Bapa","kami","yang","di","surga","dikuduskanlah","nama-Mu"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 48, '{"reference":"Yohanes 15:13","words":["Tidak","ada","kasih","yang","lebih","besar","dari","pada","kasih","seorang","yang","memberikan","nyawanya"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10,11,12]}'),
('verse_scramble', 49, '{"reference":"Roma 3:23","words":["Karena","semua","orang","telah","berbuat","dosa","dan","kehilangan","kemuliaan","Allah"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 50, '{"reference":"Roma 6:23","words":["Upah","dosa","ialah","maut","tetapi","karunia","Allah","ialah","hidup","yang","kekal"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 51, '{"reference":"Keluaran 20:3","words":["Jangan","ada","padamu","allah","lain","di","hadapan-Ku"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 52, '{"reference":"Matius 28:20","words":["Dan","ketahuilah","Aku","menyertai","kamu","senantiasa","sampai","kepada","akhir","zaman"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 53, '{"reference":"Mazmur 121:1","words":["Aku","melayangkan","mataku","ke","gunung-gunung","dari","manakah","datang","pertolonganku"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 54, '{"reference":"Wahyu 21:4","words":["Ia","akan","menghapus","segala","air","mata","dari","mata","mereka"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 55, '{"reference":"2 Korintus 5:17","words":["Siapa","yang","ada","di","dalam","Kristus","ia","adalah","ciptaan","baru"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 56, '{"reference":"Yakobus 4:8","words":["Mendekatlah","kepada","Allah","dan","Ia","akan","mendekat","kepadamu"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 57, '{"reference":"Mazmur 56:4","words":["Kepada","Allah","aku","percaya","aku","tidak","takut"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 58, '{"reference":"1 Petrus 5:7","words":["Serahkanlah","segala","kekuatiranmu","kepada-Nya","sebab","Ia","memelihara","kamu"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 59, '{"reference":"Kolose 3:23","words":["Apapun","juga","yang","kamu","perbuat","perbuatlah","dengan","segenap","hatimu"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 60, '{"reference":"Matius 5:16","words":["Hendaklah","terangmu","bercahaya","di","depan","orang","supaya","mereka","memuliakan","Bapamu"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 61, '{"reference":"Matius 7:7","words":["Mintalah","maka","akan","diberikan","kepadamu","carilah","maka","kamu","akan","mendapat"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 62, '{"reference":"Yohanes 8:32","words":["Kamu","akan","mengetahui","kebenaran","dan","kebenaran","itu","akan","memerdekakan","kamu"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 63, '{"reference":"Ibrani 12:1","words":["Marilah","kita","berlomba","dengan","tekun","dalam","perlombaan","yang","diwajibkan","bagi","kita"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 64, '{"reference":"Yesaya 9:6","words":["Kepada","kitalah","seorang","anak","telah","lahir","seorang","putera","telah","diberikan"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 65, '{"reference":"Yohanes 10:10","words":["Aku","datang","supaya","mereka","mempunyai","hidup","berlimpah-limpah"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 66, '{"reference":"Galatia 5:22","words":["Buah","Roh","ialah","kasih","sukacita","damai","sejahtera","kesabaran"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 67, '{"reference":"Mazmur 100:4","words":["Masuklah","melalui","pintu-gerbang-Nya","dengan","nyanyian","syukur"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 68, '{"reference":"Mazmur 37:4","words":["Bergembiralah","karena","TUHAN","maka","Ia","akan","memberikan","keinginan","hatimu"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 69, '{"reference":"Mazmur 103:12","words":["Sejauh","timur","dari","barat","demikianlah","pelanggaran","kita","dijauhkan-Nya"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 70, '{"reference":"Mazmur 37:5","words":["Serahkanlah","hidupmu","kepada","TUHAN","percayalah","kepada-Nya","Ia","akan","bertindak"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 71, '{"reference":"Matius 5:3","words":["Berbahagialah","orang","yang","miskin","di","hadapan","Allah"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 72, '{"reference":"Amsal 9:10","words":["Permulaan","hikmat","adalah","takut","akan","TUHAN"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 73, '{"reference":"Amsal 4:23","words":["Jagalah","hatimu","dengan","segala","kewaspadaan","karena","dari","situlah","terpancar","kehidupan"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 74, '{"reference":"Mazmur 16:8","words":["Aku","senantiasa","memandang","kepada","TUHAN","Ia","berdiri","di","sebelah","kananku"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 75, '{"reference":"Bilangan 6:24","words":["TUHAN","memberkati","engkau","dan","melindungi","engkau"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 76, '{"reference":"Yohanes 1:14","words":["Firman","itu","telah","menjadi","manusia","dan","diam","di","antara","kita"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 77, '{"reference":"Mazmur 51:10","words":["Jadikanlah","hatiku","tahir","ya","Allah","baharuilah","batinku","dengan","roh","yang","teguh"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 78, '{"reference":"Kisah Para Rasul 4:12","words":["Keselamatan","tidak","ada","di","dalam","siapapun","juga","selain","di","dalam","Dia"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 79, '{"reference":"Mazmur 139:14","words":["Aku","bersyukur","kepada-Mu","karena","kejadianku","dahsyat","dan","ajaib"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 80, '{"reference":"Markus 12:30","words":["Kasihilah","Tuhan","Allahmu","dengan","segenap","hatimu","jiwamu","akal","budimu","dan","kekuatanmu"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 81, '{"reference":"Efesus 4:32","words":["Hendaklah","kamu","ramah","seorang","terhadap","yang","lain","penuh","kasih","mesra"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 82, '{"reference":"2 Tawarikh 7:14","words":["Umat-Ku","yang","atas","namanya","nama-Ku","disebut","merendahkan","diri","berdoa","dan","mencari","wajah-Ku"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10,11]}'),
('verse_scramble', 83, '{"reference":"1 Samuel 16:7","words":["Manusia","melihat","apa","yang","di","depan","mata","tetapi","TUHAN","melihat","hati"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 84, '{"reference":"Yohanes 6:35","words":["Akulah","roti","hidup","barangsiapa","datang","kepada-Ku","ia","tidak","akan","lapar"],"correct_order":[0,1,2,3,4,5,6,7,8,9]}'),
('verse_scramble', 85, '{"reference":"1 Tesalonika 5:16","words":["Bersukacitalah","senantiasa"],"correct_order":[0,1]}'),
('verse_scramble', 86, '{"reference":"Mazmur 62:6","words":["Hanya","pada","Allah","saja","kiranya","jiwaku","tenang","sebab","dari","pada-Nyalah","harapanku"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 87, '{"reference":"Lukas 12:32","words":["Janganlah","takut","hai","kamu","kawanan","kecil"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 88, '{"reference":"Mazmur 55:22","words":["Serahkanlah","bebanmu","kepada","TUHAN","Ia","akan","menanggung","kamu"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 89, '{"reference":"Yesaya 26:3","words":["Yang","hatinya","teguh","Kaujaga","dengan","damai","sejahtera"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 90, '{"reference":"Yohanes 16:33","words":["Kuatkanlah","hatimu","Aku","telah","mengalahkan","dunia"],"correct_order":[0,1,2,3,4,5]}'),
('verse_scramble', 91, '{"reference":"Roma 8:1","words":["Tidak","ada","penghukuman","bagi","mereka","yang","ada","di","dalam","Kristus","Yesus"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 92, '{"reference":"Yesaya 43:2","words":["Apabila","engkau","berjalan","melalui","air","Aku","akan","menyertai","engkau"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 93, '{"reference":"Mazmur 145:18","words":["TUHAN","dekat","kepada","semua","orang","yang","berseru","kepada-Nya"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 94, '{"reference":"Kolose 1:17","words":["Ia","ada","terlebih","dahulu","dari","segala","sesuatu","dan","segala","sesuatu","ada","di","dalam","Dia"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10,11,12,13]}'),
('verse_scramble', 95, '{"reference":"Matius 11:28","words":["Marilah","kepada-Ku","semua","yang","kelelahan","dan","berbeban","berat"],"correct_order":[0,1,2,3,4,5,6,7]}'),
('verse_scramble', 96, '{"reference":"Mazmur 18:2","words":["TUHAN","adalah","sandaranku","kubu","pertahananku","dan","penyelamatku"],"correct_order":[0,1,2,3,4,5,6]}'),
('verse_scramble', 97, '{"reference":"Mazmur 29:11","words":["TUHAN","kiranya","memberkati","umat-Nya","dengan","kekuatan","dan","damai","sejahtera"],"correct_order":[0,1,2,3,4,5,6,7,8]}'),
('verse_scramble', 98, '{"reference":"Ibrani 4:12","words":["Firman","Allah","hidup","dan","kuat","lebih","tajam","dari","pedang","bermata","dua"],"correct_order":[0,1,2,3,4,5,6,7,8,9,10]}'),
('verse_scramble', 99, '{"reference":"Mazmur 34:8","words":["Kecaplah","dan","lihatlah","betapa","baiknya","TUHAN"],"correct_order":[0,1,2,3,4,5]}');

insert into questions (game_type, order_index, content) values
('emoji_story', 0, '{"emojis":"⛵🦁🐘🕊️🌈","hint":"Kejadian 6-9","words":["Nuh","bahtera","banjir","Musa","hewan","Daud","pelangi","Yesus","air","Goliat"],"correct":[0,1,2,4,6]}'),
('emoji_story', 1, '{"emojis":"⛵🌊🐋🙏","hint":"Yunus 1-2","words":["Elia","Yunus","laut","ditelan","Petrus","ikan besar","Yohanes","berdoa","Lazarus","badai"],"correct":[1,2,3,5,7]}'),
('emoji_story', 2, '{"emojis":"👶🧺🌊🌾","hint":"Keluaran 2:3","words":["Nuh","Musa","bayi","Yusuf","keranjang","sungai Nil","bahtera","buluh","Elisa","pelangi"],"correct":[1,2,4,5,7]}'),
('emoji_story', 3, '{"emojis":"🌿🔥👡👡","hint":"Keluaran 3:2","words":["semak","terbakar","Elisa","Daniel","sandal","suci","Tuhan","Yunus","Daud","manna"],"correct":[0,1,4,5,6]}'),
('emoji_story', 4, '{"emojis":"🌊✋🚶🚶🌊","hint":"Keluaran 14:21","words":["Yordan","Musa","Goliat","laut merah","tongkat","membelah","Daniel","Israel","Betlehem","Firaun"],"correct":[1,3,4,7,9]}'),
('emoji_story', 5, '{"emojis":"⛰️🔥🪨🪨","hint":"Keluaran 20","words":["Yosua","Sinai","loh batu","perintah","Samuel","Musa","Tuhan","Gideon","Babel","manna"],"correct":[1,2,3,5,6]}'),
('emoji_story', 6, '{"emojis":"☁️⬇️🍞🍞🍞","hint":"Keluaran 16:15","words":["manna","Elia","padang gurun","langit","Nuh","Israel","lapar","Kana","air anggur","Yordan"],"correct":[0,2,3,5,6]}'),
('emoji_story', 7, '{"emojis":"🪨🪨🪨🏹👦","hint":"1 Samuel 17","words":["Simson","Daud","ketapel","Yunus","batu","Filistin","Rut","Goliat","domba","sungai"],"correct":[1,2,4,5,7]}'),
('emoji_story', 8, '{"emojis":"💇✂️💪😴","hint":"Hakim-hakim 16","words":["Daud","Simson","Dalila","rambut","Rut","kekuatan","gunting","Goliat","Debora","tongkat"],"correct":[1,2,3,5,6]}'),
('emoji_story', 9, '{"emojis":"🦁🦁🦁🙏🌙","hint":"Daniel 6","words":["Yunus","Daniel","singa","gua","Nehemia","berdoa","malaikat","Saulus","Elia","perapian"],"correct":[1,2,3,5,6]}'),
('emoji_story', 10, '{"emojis":"👨👨👨🔥🔥👼","hint":"Daniel 3","words":["perapian","api","Yunus","tiga orang","malaikat","Gideon","Nebukadnezar","Yusuf","Simson","singa"],"correct":[0,1,3,4,6]}'),
('emoji_story', 11, '{"emojis":"🌈👘🕳️😢","hint":"Kejadian 37","words":["Daud","Yusuf","jubah warna-warni","sumur","saudara","Musa","iri hati","Goliat","bahtera","Nuh"],"correct":[1,2,3,4,6]}'),
('emoji_story', 12, '{"emojis":"🌟👶🐑🏚️","hint":"Lukas 2:7","words":["Nazaret","Betlehem","palungan","gembala","Yerusalem","bintang","bayi","majus","Yohanes","malam"],"correct":[1,2,3,5,6]}'),
('emoji_story', 13, '{"emojis":"⭐🐪🐪🐪🎁🎁🎁","hint":"Matius 2:2","words":["gembala","orang majus","bintang","unta","hadiah","Herodes","palungan","Nazaret","sungai","malam"],"correct":[1,2,3,4,5]}'),
('emoji_story', 14, '{"emojis":"💧💧🕊️☁️","hint":"Matius 3:16","words":["Yesus","Yordan","Kana","Yohanes","merpati","Getsemani","Roh Kudus","Betlehem","Sinai","anggur"],"correct":[0,1,3,4,6]}'),
('emoji_story', 15, '{"emojis":"🍞🍞🍞🍞🍞🐟🐟","hint":"Yohanes 6:9","words":["Kana","lima ribu","air anggur","dua ikan","anak kecil","lima roti","Yordan","berkelimpahan","manna","pesta"],"correct":[1,3,4,5,7]}'),
('emoji_story', 16, '{"emojis":"🌊👣⛵","hint":"Matius 14:29","words":["Yordan","air","Petrus","Kana","tenggelam","iman","perahu","Yohanes","Getsemani","laut merah"],"correct":[1,2,4,5,6]}'),
('emoji_story', 17, '{"emojis":"⛵⛈️🌊✋","hint":"Markus 4:39","words":["Kana","badai","perahu","tidur","laut merah","diam","danau","anggur","Yordan","manna"],"correct":[1,2,3,5,6]}'),
('emoji_story', 18, '{"emojis":"👁️🙈✋💧","hint":"Yohanes 9:7","words":["air","buta","kusta","mata","lumpur","Yordan","lihat","sembuh","Kana","Lazarus"],"correct":[1,3,4,6,7]}'),
('emoji_story', 19, '{"emojis":"😢⚰️🪨✋","hint":"Yohanes 11:43","words":["Yairus","Lazarus","mati","gua kubur","Nuh","empat hari","Maria","Elisa","tiga hari","kebangkitan"],"correct":[1,2,3,5,6]}'),
('emoji_story', 20, '{"emojis":"💰🏃🐷🏠","hint":"Lukas 15:11","words":["domba","babi","jauh negeri","uang perak","berhura-hura","ayah","kembali","anak sulung","gembala","padang"],"correct":[1,2,4,5,6]}'),
('emoji_story', 21, '{"emojis":"🤕🛣️🫏🩹🪙🪙","hint":"Lukas 10:33","words":["Samaria","luka","Yerikho","keledai","Lewi","penginapan","minyak","Elia","domba","Yordan"],"correct":[0,1,3,5,6]}'),
('emoji_story', 22, '{"emojis":"🍞🍷🕯️🙏","hint":"Matius 26:26","words":["roti","anggur","Kana","12 murid","pernikahan","Yudas","malam","Betlehem","Getsemani","Pilatus"],"correct":[0,1,3,5,6]}'),
('emoji_story', 23, '{"emojis":"✝️⛰️🩸🌑","hint":"Yohanes 19:17","words":["Getsemani","salib","Golgota","mahkota duri","kubur","Pilatus","mati","Nazaret","baptisan","Yudas"],"correct":[1,2,3,5,6]}'),
('emoji_story', 24, '{"emojis":"🪨⬅️⚰️👼","hint":"Matius 28:6","words":["Lazarus","kubur kosong","malaikat","Elisa","Maria Magdalena","tiga hari","bangkit","Yairus","Golgota","salib"],"correct":[1,2,4,5,6]}'),
('emoji_story', 25, '{"emojis":"💨🔥🔥🗣️🌍","hint":"Kisah Para Rasul 2:4","words":["baptisan","api","lidah","Yordan","angin","bahasa","Roh Kudus","Kana","Sinai","merpati"],"correct":[1,2,4,5,6]}'),
('emoji_story', 26, '{"emojis":"🐓❌❌❌","hint":"Lukas 22:61","words":["Yudas","ayam","tiga kali","menyangkal","Pilatus","Petrus","malam","Golgota","salib","Herodes"],"correct":[1,2,3,5,6]}'),
('emoji_story', 27, '{"emojis":"🧱🏗️🗼🌍","hint":"Kejadian 11:4","words":["Yerikho","menara","Babel","bahasa dikacaukan","Niniwe","batu bata","berserakan","Nehemia","tembok","Nuh"],"correct":[1,2,3,5,6]}'),
('emoji_story', 28, '{"emojis":"🍎🐍🌳👫","hint":"Kejadian 3:6","words":["Adam","Kain","Hawa","ular","Nuh","buah terlarang","Eden","bahtera","Lot","malaikat"],"correct":[0,2,3,5,6]}'),
('emoji_story', 29, '{"emojis":"🪵🥩🌊🔥⬇️","hint":"1 Raja-raja 18:38","words":["Horeb","Karmel","Baal","Yosua","api dari langit","persembahan","hujan","Samuel","Gideon","Daniel"],"correct":[1,2,4,5,6]}'),
('emoji_story', 30, '{"emojis":"🌳👀💰🏃","hint":"Lukas 19:4","words":["Nicodemus","Zakheus","ara","pemungut cukai","Simon","pendek","bertobat","Bartimeus","Yerikho","domba"],"correct":[1,2,3,5,6]}'),
('emoji_story', 31, '{"emojis":"💰💰💰😢🚶","hint":"Matius 19:22","words":["kaya","perintah","Bartimeus","menjual semua","Zakheus","sedih","pergi","domba","uang perak","Simon"],"correct":[0,1,3,5,6]}'),
('emoji_story', 32, '{"emojis":"🐑❓🔍🎊","hint":"Lukas 15:5","words":["uang perak","domba","99","anak hilang","hilang","dicari","bersukacita","gembala","Samaria","Lewi"],"correct":[1,2,4,5,6]}'),
('emoji_story', 33, '{"emojis":"🏺🏺🏺💧🍷","hint":"Yohanes 2:9","words":["manna","Kana","tempayan","air","laut merah","anggur","pesta","Yordan","baptisan","gembala"],"correct":[1,2,3,5,6]}'),
('emoji_story', 34, '{"emojis":"⛰️🗡️👦🔥🐑","hint":"Kejadian 22:2","words":["Yakub","Abraham","Ishak","Moria","Esau","pisau","domba jantan","malaikat","Sinai","Nuh"],"correct":[1,2,3,5,6]}'),
('emoji_story', 35, '{"emojis":"💍👑🏰👸","hint":"Ester 2:17","words":["Rut","Ester","Ahasyweros","Mordekhai","Debora","ratu","mahkota","Naomi","Salomo","Haman"],"correct":[1,2,3,5,6]}'),
('emoji_story', 36, '{"emojis":"👶👩👩🗡️👑","hint":"1 Raja-raja 3:25","words":["Salomo","Daud","dua ibu","bayi","Ester","pedang","hikmat","Rut","Ahasyweros","mahkota"],"correct":[0,2,3,5,6]}'),
('emoji_story', 37, '{"emojis":"⛓️⛓️🎵🌋🚪","hint":"Kisah Para Rasul 16:25","words":["Petrus","Paulus","Silas","penjara","Yerusalem","menyanyi","gempa","Daniel","singa","Stefanus"],"correct":[1,2,3,5,6]}'),
('emoji_story', 38, '{"emojis":"⛵⛈️💥🌊🏊","hint":"Kisah Para Rasul 27:41","words":["Yunus","Paulus","kapal","badai","Nuh","Malta","selamat","ikan besar","bahtera","Silas"],"correct":[1,2,3,5,6]}'),
('emoji_story', 39, '{"emojis":"⛰️👗☀️👼","hint":"Matius 17:2","words":["Musa","Yohanes","Elia","gunung","Sinai","putih bersinar","Petrus","Yordan","baptisan","Kana"],"correct":[0,2,3,5,6]}'),
('emoji_story', 40, '{"emojis":"🫏🌿🌿🙌🏙️","hint":"Matius 21:8","words":["Betlehem","keledai","palem","Nazaret","Yerusalem","hosana","jubah","Getsemani","Golgota","salib"],"correct":[1,2,4,5,6]}'),
('emoji_story', 41, '{"emojis":"👼👩🤰","hint":"Lukas 1:28","words":["Elisabet","Gabriel","Maria","mengandung","Roh Kudus","Zakharia","jangan takut","Betlehem","Yohanes","bintang"],"correct":[1,2,3,4,6]}'),
('emoji_story', 42, '{"emojis":"🐑🐑👼⭐🌙","hint":"Lukas 2:10","words":["orang majus","gembala","malam","malaikat","bintang","kabar sukacita","Betlehem","unta","hadiah","Herodes"],"correct":[1,2,3,5,6]}'),
('emoji_story', 43, '{"emojis":"⛰️🌪️🔥🤫","hint":"1 Raja-raja 19:12","words":["Karmel","Horeb","angin","gempa","Baal","api","suara sunyi","Samuel","Elisa","Yosua"],"correct":[1,2,3,5,6]}'),
('emoji_story', 44, '{"emojis":"🧱🔨👷🏙️","hint":"Nehemia 2:17","words":["Ezra","Nehemia","tembok","Yerusalem","Babel","reruntuhan","membangun","Yosua","Daniel","Babel"],"correct":[1,2,3,5,6]}'),
('emoji_story', 45, '{"emojis":"🏺🔦🎺💥","hint":"Hakim-hakim 7:16","words":["Simson","Gideon","300 prajurit","tempayan","Saul","obor","sangkakala","Daud","Debora","Rut"],"correct":[1,2,3,5,6]}'),
('emoji_story', 46, '{"emojis":"🔥🏙️🔙🧂🗿","hint":"Kejadian 19:26","words":["Abraham","Lot","Sodom","menoleh","Rebekah","tiang garam","malaikat","Nuh","Babel","Ester"],"correct":[1,2,3,5,6]}'),
('emoji_story', 47, '{"emojis":"🎺🎺🎺🏰💥","hint":"Yosua 6:20","words":["Nehemia","Yerikho","sangkakala","tujuh hari","Babel","tembok runtuh","Yosua","Gideon","Simson","menara"],"correct":[1,2,3,5,6]}'),
('emoji_story', 48, '{"emojis":"👩👩🌾🌾🌾","hint":"Rut 2:3","words":["Ester","Rut","Naomi","Boaz","Debora","jelai","memungut","Mordekhai","ladang","Ahasyweros"],"correct":[1,2,3,5,6]}'),
('emoji_story', 49, '{"emojis":"🏇⚡🙈🙏","hint":"Kisah Para Rasul 9:3","words":["Stefanus","Saulus","Damsyik","cahaya","Silas","jatuh","buta","Petrus","Yerusalem","Ananias"],"correct":[1,2,3,5,6]}');
